### ISSUE TITLE
Export crashes

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#209]
Beginning with 700 components, the Excel export seems to crash, requires testing first to ensure it is not because of not-supported characters.

**Comment by mcjaeger** [comment]
requires dataset for import

**Comment by mcjaeger** [comment]
with this dataset (about 700 release and 400 components), the only thing I can see is:
```
2016-11-01 22:35:29,507 ERROR ComponentPortlet:239 - An error occurred while generating the Excel export
 SW360Exception(why:Error fetching release information)
        at com.siemens.sw360.exporter.ComponentExporter$ComponentHelper.getReleases(ComponentExporter.java:173)
        at com.siemens.sw360.exporter.ComponentExporter$ComponentHelper.makeRowsWithReleases(ComponentExporter.java:105)
        at com.siemens.sw360.exporter.ComponentExporter$ComponentHelper.makeRows(ComponentExporter.java:100)
        at com.siemens.sw360.exporter.ComponentExporter$ComponentHelper.makeRows(ComponentExporter.java:78)
        at com.siemens.sw360.exporter.ExcelExporter.fillValues(ExcelExporter.java:74)
        at com.siemens.sw360.exporter.ExcelExporter.makeExcelExport(ExcelExporter.java:52)
        at com.siemens.sw360.portal.portlets.components.ComponentPortlet.exportExcel(ComponentPortlet.java:236)
        at com.siemens.sw360.portal.portlets.components.ComponentPortlet.serveResource(ComponentPortlet.java:137)
        at com.liferay.portlet.FilterChainImpl.doFilter(FilterChainImpl.java:122)
```
regardsless if that is for components only or components with releases

**Comment by mcjaeger** [comment]
works with 220 components and 220 components+255 releases

**Comment by alex-evo** [comment]
Do I recall correctly that we've seen another error message in your log last time we met? What was it?

**Comment by alex-evo** [comment]
I cannot reproduce the problem. I dimly remember now that we've seen some sign of a problem with the data in your DB.
Please confirm it that was the case.

**Comment by mcjaeger** [comment]
does not crash anymore on productive instance. Cannot reproduce therefore anymore.
