### ISSUE TITLE
Downloading attachments unreliable due to connection leak

### ISSUE THREAD

**Issue by alex-evo** [sw360/sw360portal#217]
Problem discovered while testing license info file generation with SPDX attachments. License info file could not be generated because the `SPDXParser` stumbled on a "ConnectionPoolTimeoutException: Timeout waiting for connection"

Restarting the server remedies the problem for a while.
Top suspect is the `AttachmentConnector.getSha1FromAttachmentContentId(...)` method, where the attachmentStream is not closed (wrapping with `AutoCloseInputStream` should do the trick), but it may have other accomplices.

**Comment by mcjaeger** [comment]
it seems like I can confirm this, this happened when trying to build a readme with 45 releases:

```
 2016-09-01 15:17:08 ERROR Sw360ThriftServlet:42 - uncaught
 org.ektorp.DbAccessException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at org.ektorp.util.Exceptions.propagate(Exceptions.java:19)
        at org.ektorp.http.StdHttpClient.executeRequest(StdHttpClient.java:183)
        at org.ektorp.http.StdHttpClient.executeRequest(StdHttpClient.java:192)
        at org.ektorp.http.StdHttpClient.get(StdHttpClient.java:82)
        at org.ektorp.http.RestTemplate.get(RestTemplate.java:31)
        at org.ektorp.impl.StdCouchDbConnector.getAttachment(StdCouchDbConnector.java:213)
        at org.ektorp.impl.StdCouchDbConnector.getAttachment(StdCouchDbConnector.java:198)
        at com.siemens.sw360.datahandler.couchdb.AttachmentStreamConnector$1.next(AttachmentStreamConnector.java:124)
        at com.siemens.sw360.datahandler.couchdb.AttachmentStreamConnector$1.next(AttachmentStreamConnector.java:110)
2016-09-01 15:17:08,627 ERROR ProjectPortlet:139 - Error getting LicenseInfo file
 org.apache.thrift.transport.TTransportException: HTTP Response code: 500
        at org.apache.thrift.transport.THttpClient.flush(THttpClient.java:349)
        at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:73)
        at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
        at com.siemens.sw360.datahandler.thrift.licenseinfo.LicenseInfoService$Client.send_getLicenseInfoFileForProject(LicenseInfoService.java:155)
        at com.siemens.sw360.datahandler.thrift.licenseinfo.LicenseInfoService$Client.getLicenseInfoFileForProject(LicenseInfoService.java:146)
        at com.siemens.sw360.portal.portlets.projects.ProjectPortlet.downloadLicenseInfo(ProjectPortlet.java:137)
        at com.siemens.sw360.portal.portlets.projects.ProjectPortlet.serveResource(ProjectPortlet.java:121)
        at com.liferay.portlet.FilterChainImpl.doFilter(FilterChainImpl.java:122)
        at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:82)
```
(this is the complete stacktrace of what is in the log)

**Comment by heydenreich** [comment]
If closing the stream is the only thing to do, it is size S.
