### ISSUE TITLE
License Info Generation Fails

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#238]
Did the following for each of the SPDX files contained in this archive:
[SPDX example files.zip(https://github.com/sw360/sw360portal/files/478322/SPDX.example.files.zip)
(based on SPDX tool 2.0.4 examples, replaced license texts for better traceability with letters 'b', 'c' and 'd'):
1. create component
2. create release
3. attach SPDX file with type component license information
4. create project
5. link the release with the SPDX just created, only this one

-> works fine

BUT ... trying again:
1. create component and release with one of the example SPDX 
2. repeat for second and third component
3. create a project
4. add the three releases this one project
5. generate license info (does not matter whether text, docx, html)

-> white page return with stack trace

`2016-09-17 18:54:59 ERROR Sw360ThriftServlet:42 - uncaught
 org.ektorp.DbAccessException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
    at org.ektorp.util.Exceptions.propagate(Exceptions.java:19)
    at org.ektorp.http.StdHttpClient.executeRequest(StdHttpClient.java:183)
    at org.ektorp.http.StdHttpClient.executeRequest(StdHttpClient.java:192)
    at org.ektorp.http.StdHttpClient.get(StdHttpClient.java:82)
    at org.ektorp.http.RestTemplate.get(RestTemplate.java:31)
    at org.ektorp.impl.StdCouchDbConnector.getAttachment(StdCouchDbConnector.java:213)
    at org.ektorp.impl.StdCouchDbConnector.getAttachment(StdCouchDbConnector.java:198)
    at com.siemens.sw360.datahandler.couchdb.AttachmentStreamConnector$1.next(AttachmentStreamConnector.java:124)
    at com.siemens.sw360.datahandler.couchdb.AttachmentStreamConnector$1.next(AttachmentStreamConnector.java:110)
2016-09-17 18:54:59,309 ERROR ProjectPortlet:168 - Error getting LicenseInfo file
 org.apache.thrift.transport.TTransportException: HTTP Response code: 500
    at org.apache.thrift.transport.THttpClient.flush(THttpClient.java:349)
    at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:73)
    at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
    at com.siemens.sw360.datahandler.thrift.licenseinfo.LicenseInfoService$Client.send_getLicenseInfoFileForProject(LicenseInfoService.java:178)
    at com.siemens.sw360.datahandler.thrift.licenseinfo.LicenseInfoService$Client.getLicenseInfoFileForProject(LicenseInfoService.java:168)
    at com.siemens.sw360.portal.portlets.projects.ProjectPortlet.downloadLicenseInfo(ProjectPortlet.java:165)
    at com.siemens.sw360.portal.portlets.projects.ProjectPortlet.serveResource(ProjectPortlet.java:139)
    at com.liferay.portlet.FilterChainImpl.doFilter(FilterChainImpl.java:122)
    at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:82)`

So, the strange point is that generation works for each of the SPDX files when the referring release is the only one added to a project. It sounds similar to: 
https://github.com/sw360/sw360portal/issues/217

**Comment by mcjaeger** [comment]
actually it turned out that the white page was a safari issue, it works with firefox and chrome on a mac.
