### ISSUE TITLE
cve-search unit tests fail in a proxy environmnt

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#279]
no news, just creating a ticket because I was stumbling over it now again. I think it would be better to be able to execute the maven chain without -s / -Dskiptests on the long run. Attached the stack trace

IMHO, the proxy setting are not there for the entity that is trying to call out. Maybe calling out during the unit testing is generally prone to errors, as not everyone has everytime a working Internet connection.

@alex-evo you have had this error too, right?

```
==> default: [INFO] --- maven-surefire-plugin:2.10:test (default-test) @ src-cvesearch ---
==> default: [INFO] Surefire report directory: /sw360portal/backend/src/src-cvesearch/target/surefire-reports
==> default: -------------------------------------------------------
==> default:  T E S T S
==> default: -------------------------------------------------------
==> default: OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
==> default: Running com.bosch.osmi.sw360.cvesearch.entitytranslation.CveSearchDataTranslatorTest
==> default: Tests run: 5, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 255.625 sec <<< FAILURE!
==> default: Running com.bosch.osmi.sw360.cvesearch.datasink.VulnerabilityConnectorTest
==> default: Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.183 sec
==> default: Running com.bosch.osmi.sw360.cvesearch.datasource.json.CveSearchJsonParserTest
==> default: Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.064 sec
==> default: Running com.bosch.osmi.sw360.cvesearch.datasource.heuristics.SearchLevelsTest
==> default: Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.023 sec
==> default: Running com.bosch.osmi.sw360.cvesearch.datasource.CveSearchWrapperTest
==> default: Tests run: 3, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 127.308 sec <<< FAILURE!
==> default: Running com.bosch.osmi.sw360.cvesearch.datasource.matcher.ModifiedLevenshteinDistanceTest
==> default: Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec
==> default: Running com.bosch.osmi.sw360.cvesearch.datasource.matcher.ListMatcherTest
==> default: Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 sec
==> default: Running com.bosch.osmi.sw360.cvesearch.datasource.CveSearchGuesserTest
==> default: 2016-11-16 08:39:38 ERROR CveSearchGuesser:67 - Connection timed out (Connection timed out)
==> default:  java.net.ConnectException: Connection timed out (Connection timed out)
==> default:    at java.net.PlainSocketImpl.socketConnect(Native Method)
==> default:    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
==> default:    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
==> default:    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
==> default:    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
==> default:    at java.net.Socket.connect(Socket.java:589)
==> default:    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
==> default:    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
==> default:    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
==> default: 2016-11-16 08:41:45 ERROR CveSearchGuesser:55 - Connection timed out (Connection timed out)
==> default:  java.net.ConnectException: Connection timed out (Connection timed out)
==> default:    at java.net.PlainSocketImpl.socketConnect(Native Method)
==> default:    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
==> default:    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
==> default:    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
==> default:    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
==> default:    at java.net.Socket.connect(Socket.java:589)
==> default:    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
==> default:    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
==> default:    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
==> default: 2016-11-16 08:43:53 ERROR CveSearchGuesser:55 - Connection timed out (Connection timed out)
==> default:  java.net.ConnectException: Connection timed out (Connection timed out)
==> default:    at java.net.PlainSocketImpl.socketConnect(Native Method)
==> default:    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
==> default:    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
==> default:    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
==> default:    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
==> default:    at java.net.Socket.connect(Socket.java:589)
==> default:    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
==> default:    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
==> default:    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
==> default: Tests run: 4, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 381.802 sec <<< FAILURE!
==> default: Running com.bosch.osmi.sw360.cvesearch.datasource.CveSearchApiImplTest
==> default: Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 381.698 sec <<< FAILURE!
==> default: Running com.bosch.osmi.sw360.cvesearch.helper.VulnerabilityUtilsTest
==> default: Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec
==> default:
==> default: Results :
==> default:
==> default: Tests in error:
==> default:   testWithRealData(com.bosch.osmi.sw360.cvesearch.entitytranslation.CveSearchDataTranslatorTest): Connection timed out (Connection timed out)
==> default:   testWithApacheData(com.bosch.osmi.sw360.cvesearch.entitytranslation.CveSearchDataTranslatorTest): Connection timed out (Connection timed out)
==> default:   compareToSearchByCPE(com.bosch.osmi.sw360.cvesearch.datasource.CveSearchWrapperTest): Connection timed out (Connection timed out)
==> default:   guessProductTestMavenFullMatch(com.bosch.osmi.sw360.cvesearch.datasource.CveSearchGuesserTest): Was not able to instantiate product guesser for vendor apache
==> default:   guessVendorTestApacheFullMatch(com.bosch.osmi.sw360.cvesearch.datasource.CveSearchGuesserTest): Was not able to instantiate vendor guesser
==> default:   guessProductTestApacheFullMatchWithThreshold(com.bosch.osmi.sw360.cvesearch.datasource.CveSearchGuesserTest): Was not able to instantiate vendor guesser
==> default:   exactCveforTest(com.bosch.osmi.sw360.cvesearch.datasource.CveSearchApiImplTest): Connection timed out (Connection timed out)
==> default:   exactSearchTest(com.bosch.osmi.sw360.cvesearch.datasource.CveSearchApiImplTest): Connection timed out (Connection timed out)
==> default:   exactCveTest(com.bosch.osmi.sw360.cvesearch.datasource.CveSearchApiImplTest): Connection timed out (Connection timed out)

```

**Comment by alex-evo** [comment]
Right. Still have it.
