### ISSUE TITLE
Rarely, Adding a Release Fails

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#316]
At rare cases, adding a release fails with stack trace given below, walk through:

* For an existing component with releases: Edit, Add Release
* Enter just release version number and CPE
* Click "Add Release" yields "Components not available" with the stack trace below

Trick is that retesting usually does not show the same behavior.  It is also not the same release version.

Issue is created to keep track on further occurrences. First tracing has come out with the assumption @alex-evo that the Javascript may not work correctly when clicking "Add Release" from the component's release overview.

```
2016-12-22 13:43:24 ERROR SW360Assert:116 - Invalid empty input!
 SW360Exception(why:null)
        at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:110)
        at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:74)
        at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:69)
        at org.eclipse.sw360.vendors.VendorHandler.getByID(VendorHandler.java:48)
        at org.eclipse.sw360.datahandler.thrift.vendors.VendorService$Processor$getByID.getResult(VendorService.java:643)
        at org.eclipse.sw360.datahandler.thrift.vendors.VendorService$Processor$getByID.getResult(VendorService.java:628)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.thrift.server.TServlet.doPost(TServlet.java:83)
2016-12-22 13:43:24 ERROR ProcessFunction:41 - Internal error processing getByID
 SW360Exception(why:Invalid empty input!)
        at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:117)
        at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:111)
        at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:74)
        at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotEmpty(SW360Assert.java:69)
        at org.eclipse.sw360.vendors.VendorHandler.getByID(VendorHandler.java:48)
        at org.eclipse.sw360.datahandler.thrift.vendors.VendorService$Processor$getByID.getResult(VendorService.java:643)
        at org.eclipse.sw360.datahandler.thrift.vendors.VendorService$Processor$getByID.getResult(VendorService.java:628)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
2016-12-22 13:43:24,447 ERROR ComponentPortlet:844 - Error fetching release from backend!
 org.apache.thrift.TApplicationException: Internal error processing getByID
        at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
        at org.eclipse.sw360.datahandler.thrift.vendors.VendorService$Client.recv_getByID(VendorService.java:162)
        at org.eclipse.sw360.datahandler.thrift.vendors.VendorService$Client.getByID(VendorService.java:149)
        at org.eclipse.sw360.portal.portlets.components.ComponentPortlet.fillVendor(ComponentPortlet.java:861)
        at org.eclipse.sw360.portal.portlets.components.ComponentPortlet.prepareRequestForReleaseEditAfterDuplicateError(ComponentPortlet.java:850)
        at org.eclipse.sw360.portal.portlets.components.ComponentPortlet.updateRelease(ComponentPortlet.java:834)
        at sun.reflect.GeneratedMethodAccessor1768.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:43:24,455 ERROR [http-bio-8080-exec-10403][PortletServlet:116] javax.portlet.PortletException: Component and Release ID not set!
javax.portlet.PortletException: Component and Release ID not set!
        at org.eclipse.sw360.portal.portlets.components.ComponentPortlet.prepareReleaseEdit(ComponentPortlet.java:401)
        at org.eclipse.sw360.portal.portlets.components.ComponentPortlet.doView(ComponentPortlet.java:350)
...
```

**Comment by mcjaeger** [comment]
I think the duplication check at creating a release that looked for prefix instead of the entire string was it.
