### ISSUE TITLE
Cannot add or edit components, releases, ...

### ISSUE THREAD

**Issue by alexbrdn** [sw360/sw360portal#553]
Testing with current master (7f7d391), I cannot add or edit components, because of the following exception:
```
09:15:09,052 ERROR [http-bio-8080-exec-25][PortletServlet:116] javax.portlet.PortletException: org.apache.jasper.JasperException: An exception occurred processing JSP page /html/components/edit.jsp at line 131__128: </core_rt:if>_129: _130: <script>_131:     var permissions = {  'write':  ${permissions.makePermission(component, currentUser).isActionAllowed(RequestedAction.DELETE)},_132:                          'delete': ${permissions.makePermission(component, currentUser).isActionAllowed(RequestedAction.WRITE)}_133:     };_134: ___Stacktrace: [Sanitized]
javax.portlet.PortletException: org.apache.jasper.JasperException: An exception occurred processing JSP page /html/components/edit.jsp at line 131__128: </core_rt:if>_129: _130: <script>_131:     var permissions = {  'write':  ${permissions.makePermission(component, currentUser).isActionAllowed(RequestedAction.DELETE)},_132:                          'delete': ${permissions.makePermission(component, currentUser).isActionAllowed(RequestedAction.WRITE)}_133:     };_134: ___Stacktrace: [Sanitized]
	at com.liferay.portlet.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:117)
	at com.liferay.util.bridges.mvc.MVCPortlet.include(MVCPortlet.java:362)
	at com.liferay.util.bridges.mvc.MVCPortlet.include(MVCPortlet.java:378)
	at org.eclipse.sw360.portal.portlets.components.ComponentPortlet.doView(ComponentPortlet.java:443)
...
Caused by: java.lang.NullPointerException
	at org.eclipse.sw360.datahandler.permissions.DocumentPermissions.getStandardPermissions(DocumentPermissions.java:87)
	at org.eclipse.sw360.datahandler.permissions.ComponentPermissions.isActionAllowed(ComponentPermissions.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

```

Looks like this [line](https://github.com/sw360/sw360portal/pull/529/files#diff-8700f57c399b868e7362066689bed832R131) from #529 has created the problem.

**Comment by alexbrdn** [comment]
Ping @ChristophNiehoff. Can you check if it's reproducible on your system?

**Comment by ChristophNiehoff** [comment]
Strange...  On my system everything runs smoothly...  @alexbrdn Could you send me the CouchDB-JSON-source of the particular component that is causing the problem?  Is is only one component or all components?  Are you testing of as admin or user?

**Comment by alexbrdn** [comment]
That line is mangled up anyway: `var permissions = {  'write':  ${permissions.makePermission(component, currentUser).isActionAllowed(RequestedAction.DELETE)},` 
the key is "write", but requested action is "DELETE".

**Comment by ChristophNiehoff** [comment]
@alexbrdn , @maierthomas   I just pushed a branch `fix/553-cannot-add-or-delete-components` which contains a first idea for a fix of this problem. As I cannot reproduce the issue, can you test whether it works. Note that the branch currently ONLY implements the fix for the projects edit page.

**Comment by alexbrdn** [comment]
I think I've got a better solution. Watch this space...

**Comment by adrian-evo** [comment]
Please note something similar happens when trying to open a license:

08:22:15,639 ERROR [http-bio-8080-exec-16][PortletServlet:116] javax.portlet.PortletException: org.apache.jasper.JasperException: An exception occurred processing JSP page /html/licenses/includes/detailTodos.jspf at line 186__183:     <input type="button" class="addButton" onclick="submitModerationRequestWhiteList()" id="moderationRequestCommentSendButton" value="Send moderation request">_184: </div>_185: _186: <jsp:include page="/html/licenses/includes/updateLicenseUtils.jsp" />_187: <script>_188:     function submitFormWhiteList() {_189:         if(permissions.write) {___Stacktrace: [Sanitized]

Caused by: org.apache.jasper.JasperException: An exception occurred processing JSP page /html/licenses/includes/detailTodos.jspf at line 186__183:     <input type="button" class="addButton" onclick="submitModerationRequestWhiteList()" id="moderationRequestCommentSendButton" value="Send moderation request">_184: </div>_185: _186: <jsp:include page="/html/licenses/includes/updateLicenseUtils.jsp" />_187: <script>_188:     function submitFormWhiteList() {_189:         if(permissions.write) {___Stacktrace: [Sanitized]
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:575)

**Comment by alexbrdn** [comment]
yep. components, releases, projects, licenses, and todos are all affected. I intend to have a fix out today
